### ISSUE TITLE
Release auth seems broken

### ISSUE THREAD

**Issue by nicholaschiang** [zeit/release-auth#17]
Whenever I try to `yarn release` on my new machine (that is currently unauthenticated), [`release`](https://github.com/vercel/release) tries to open `release-auth.zeit.sh` and complete a GitHub authentication:

![image](https://user-images.githubusercontent.com/20798889/157567267-0058a596-d362-4e34-ae28-09555875cf32.png)

**Comment by nicholaschiang** [comment]
@leerob you seem to be the last contributor here; think you could take a look at your Vercel deployment logs for me?

**Comment by leerob** [comment]
Are you on the latest version of `release`?

**Comment by leerob** [comment]
FWIW, https://release-auth.vercel.sh/ is the same thing as https://release-auth.zeit.sh.

**Comment by leerob** [comment]
Could you try it now? I think this was the issue https://github.com/vercel/release-auth/pull/18

**Comment by nicholaschiang** [comment]
Nope, still broken @leerob:
![image](https://user-images.githubusercontent.com/20798889/158626607-08bdf978-1ac2-4ccb-8fa2-a627c253e394.png)

And I just updated all my dependencies:
```

nchiang@eevee ~/repos/tweetscape (master) $ yarn release patch
[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
✔ Bumped version tag to 0.0.11
✔ Created release commit
✔ Tagged commit
✔ Pushed everything to remote
⠙ Opening GitHub authentication page^C
nchiang@eevee ~/repos/tweetscape (master) $ yarn why release
└─ tweetscape@workspace:.
   └─ release@npm:6.3.0 (via npm:^6.3.0)
```

**Comment by leerob** [comment]
Could you try one more time? Worked locally.

https://github.com/vercel/release/releases/tag/6.3.1

**Comment by nicholaschiang** [comment]
Works for me now!
